version: '3'
services:
  app:
    restart: always
    build: .
    ports:
      - 5000:5000
    links:
      - db
  db:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./db/sql/schema.sql:/docker-entrypoint-initdb.d/1_schema.sql
      - ./db/sql/data.sql:/docker-entrypoint-initdb.d/2_data.sql
    environment:
      MYSQL_ROOT_PASSWORD: sentinel
      MYSQL_DATABASE: sentinel
      MYSQL_USER: sentinel
      MYSQL_PASSWORD: sentinel